import Footer from "@/components/common/Footer";
import "./globals.css";

import NavBar from "@/components/sidebar/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` bg-zinc-200 text-zinc-500`}>
        <NavBar />
        <main className="">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
