import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` bg-black text-zinc-400`}
      >
        <Header />
        <main className="px-4 md:px-16">{children}</main>
      </body>
    </html>
  );
}
